In [ ]:
import numpy as np
import itertools
import random
import itertools as it

Функция для обнаружения и исправления ошибки

In [ ]:
def code_syndrom_error(u_f,n_f,k_f,H_f,G_f, table_syndroms, count_error_f):

  #Сформировать кодовое слово длины n из слова длины k
  v_f = np.dot(u_f,G_f)%2
  print ("u: ", u_f)
  print("v: ", v_f)

  #Внести ошибку в сформированное слово
  i_f = np.random.choice(n_f, size=count_error_f, replace=False)
  print("Ошибки: ", i_f)
  for index in (i_f):
      v_f[index] = (v_f[index]+1)%2
  error_v_f = v_f
  print("Полученное кодовое слово с ошибкой: ", error_v_f)


  #Вычислить синдром
  syndrom_error_f = np.dot(error_v_f,H_f)%2
  print("Синдромы для этого кодового слова: ", syndrom_error_f)
  if sum( syndrom_error_f) != 0:
    print("Обнаружена ошибка!")

  error_correction = table_syndroms.get(tuple(syndrom_error_f), None)
  print(error_correction)


  if tuple(syndrom_error_f) in table_syndroms:
    error_index_f = table_syndroms[tuple(syndrom_error_f)]
    for i in range(len(error_index_f)):
      if error_index_f[i]:
        error_v_f[i] = (error_v_f[i]+1)%2
        true_v_f = error_v_f
    print ("Восстановленное слово: ", true_v_f)
    if all(true_v_f == v_f):
      print("Ошибка была исправлена успешно!")
    else:
      print("Ошибка не была исправлена корректно.")
  else:
      print("Синдрома нет в таблице, ошибка не исправлена.")



3.1 Написать функцию формирования порождающей и проверочной
матриц кода Хэмминга (𝟐
𝒓 − 𝟏, 𝟐
𝒓 − 𝒓 − 𝟏, 𝟑) на основе параметра 𝒓,
а также таблицы синдромов для всех однократных ошибок.

In [ ]:
def code_h(r):
    id_for_H = np.eye(r)
    X = np.array([np.ones(r)])
    for i in range(r-1, 1, -1):
        combs = list(it.combinations(range(0, r, 1), i))
        for c in combs:
            word = np.zeros(r)
            for j in c:
                word[j] = 1
            X = np.vstack([X, word])
    H = np.vstack([X, id_for_H])
    id_for_G = np.eye(X.shape[0])
    G = np.hstack([id_for_G, X])
    syndroms = dict()
    ed = np.eye(H.shape[0])
    for i in range(ed.shape[0]-1, -1, -1):
        syndroms[tuple(ed[i, :]@H)] = ed[i, :]
    return G, H, syndroms

3.2. Провести исследование кода Хэмминга для одно-, двух- и
трёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒

r = 2

In [ ]:
G, H, syndroms = code_h(2)
print(G,'\n')
print(H,'\n')
print(syndroms,'\n')

[[1. 1. 1.]] 

[[1. 1.]
 [1. 0.]
 [0. 1.]] 

{(0.0, 1.0): array([0., 0., 1.]), (1.0, 0.0): array([0., 1., 0.]), (1.0, 1.0): array([1., 0., 0.])} 



Однократная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 1)

u:  [1]
v:  [1. 1. 1.]
Ошибки:  [0]
Полученное кодовое слово с ошибкой:  [0. 1. 1.]
Синдромы для этого кодового слова:  [1. 1.]
Обнаружена ошибка!
[1. 0. 0.]
Восстановленное слово:  [1. 1. 1.]
Ошибка была исправлена успешно!


Двукратная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 2)

u:  [1]
v:  [1. 1. 1.]
Ошибки:  [1 0]
Полученное кодовое слово с ошибкой:  [0. 0. 1.]
Синдромы для этого кодового слова:  [0. 1.]
Обнаружена ошибка!
[0. 0. 1.]
Восстановленное слово:  [0. 0. 0.]
Ошибка была исправлена успешно!


Трехкратная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 3)

u:  [1]
v:  [1. 1. 1.]
Ошибки:  [1 0 2]
Полученное кодовое слово с ошибкой:  [0. 0. 0.]
Синдромы для этого кодового слова:  [0. 0.]
None
Синдрома нет в таблице, ошибка не исправлена.


r = 3


In [ ]:
G_2, H_2, syndroms_2 = code_h(3)
print(G_2,'\n')
print(H_2,'\n')
print(syndroms_2,'\n')

[[1. 0. 0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0. 1. 1.]] 

[[1. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

{(0.0, 0.0, 1.0): array([0., 0., 0., 0., 0., 0., 1.]), (0.0, 1.0, 0.0): array([0., 0., 0., 0., 0., 1., 0.]), (1.0, 0.0, 0.0): array([0., 0., 0., 0., 1., 0., 0.]), (0.0, 1.0, 1.0): array([0., 0., 0., 1., 0., 0., 0.]), (1.0, 0.0, 1.0): array([0., 0., 1., 0., 0., 0., 0.]), (1.0, 1.0, 0.0): array([0., 1., 0., 0., 0., 0., 0.]), (1.0, 1.0, 1.0): array([1., 0., 0., 0., 0., 0., 0.])} 



Однократная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 1)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0.]
Ошибки:  [0]
Полученное кодовое слово с ошибкой:  [0. 0. 0. 1. 1. 0. 0.]
Синдромы для этого кодового слова:  [1. 1. 1.]
Обнаружена ошибка!
[1. 0. 0. 0. 0. 0. 0.]
Восстановленное слово:  [1. 0. 0. 1. 1. 0. 0.]
Ошибка была исправлена успешно!


Двухкратная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 2)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0.]
Ошибки:  [3 1]
Полученное кодовое слово с ошибкой:  [1. 1. 0. 0. 1. 0. 0.]
Синдромы для этого кодового слова:  [1. 0. 1.]
Обнаружена ошибка!
[0. 0. 1. 0. 0. 0. 0.]
Восстановленное слово:  [1. 1. 1. 0. 1. 0. 0.]
Ошибка была исправлена успешно!


Трехкратная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 3)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0.]
Ошибки:  [6 4 2]
Полученное кодовое слово с ошибкой:  [1. 0. 1. 1. 0. 0. 1.]
Синдромы для этого кодового слова:  [0. 0. 0.]
None
Синдрома нет в таблице, ошибка не исправлена.


r = 4


In [ ]:
G_3, H_3, syndroms_3 = code_h(4)
print(G_3,'\n')
print(H_3,'\n')
print(syndroms_3,'\n')

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [1. 1. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

{(0.0, 0.0, 0.0, 1.0): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]), (0.0, 0.0, 1.0, 0.0): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]), (0.0, 1.0, 0.0, 0.0): array([0., 0., 0., 0., 0., 0., 0., 0

Однократная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 1)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
Ошибки:  [13]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0.]
Синдромы для этого кодового слова:  [0. 0. 1. 0.]
Обнаружена ошибка!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Восстановленное слово:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
Ошибка была исправлена успешно!


Двухкратная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 2)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
Ошибки:  [12 14]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1.]
Синдромы для этого кодового слова:  [0. 1. 0. 1.]
Обнаружена ошибка!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Восстановленное слово:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1.]
Ошибка была исправлена успешно!


Трехкратная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 3)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0.]
Ошибки:  [14 11  9]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1.]
Синдромы для этого кодового слова:  [1. 1. 0. 0.]
Обнаружена ошибка!
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Восстановленное слово:  [1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1.]
Ошибка была исправлена успешно!


3.3 Написать функцию формирования порождающей и проверочной
матриц расширенного кода Хэмминга (𝟐
𝒓
, 𝟐
𝒓 − 𝒓 − 𝟏, 𝟑) на основе
параметра 𝒓, а также таблицы синдромов для всех однократных
ошибок

In [ ]:
def code_cool_h(r):
    G, H, syndroms = code_h(r)

    H = np.hstack([H, np.reshape(np.ones(H.shape[0]), (H.shape[0], 1))])
    H = np.vstack([H, H[-1, :]])
    H[-1, -2] = 0
    add_to_G = np.reshape(np.array([np.sum(G[i, :])%2 for i in range(G.shape[0])]), (G.shape[0], 1))
    G = np.hstack([G, add_to_G])

    syndroms = dict()
    ed = np.eye(H.shape[0])
    for i in range(ed.shape[0]-1, -1, -1):
        syndroms[tuple(ed[i, :]@H)] = ed[i, :]
    return G, H, syndroms

3.4. Провести исследование расширенного кода Хэмминга для одно-,
двух-, трёх- и четырёхкратных ошибок для 𝒓 = 𝟐, 𝟑, 𝟒

r = 2

In [ ]:
G, H, syndroms = code_cool_h(2)
print(G,'\n')
print(H,'\n')
print(syndroms,'\n')

[[1. 1. 1. 1.]] 

[[1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]] 

{(0.0, 0.0, 1.0): array([0., 0., 0., 1.]), (0.0, 1.0, 1.0): array([0., 0., 1., 0.]), (1.0, 0.0, 1.0): array([0., 1., 0., 0.]), (1.0, 1.0, 1.0): array([1., 0., 0., 0.])} 



Однократная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 1)

u:  [1]
v:  [1. 1. 1. 1.]
Ошибки:  [1]
Полученное кодовое слово с ошибкой:  [1. 0. 1. 1.]
Синдромы для этого кодового слова:  [1. 0. 1.]
Обнаружена ошибка!
[0. 1. 0. 0.]
Восстановленное слово:  [1. 1. 1. 1.]
Ошибка была исправлена успешно!


Двухкратная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 2)

u:  [1]
v:  [1. 1. 1. 1.]
Ошибки:  [1 0]
Полученное кодовое слово с ошибкой:  [0. 0. 1. 1.]
Синдромы для этого кодового слова:  [0. 1. 0.]
Обнаружена ошибка!
None
Синдрома нет в таблице, ошибка не исправлена.


Трехкратная

In [ ]:
word = [1]
code_syndrom_error(word, 3, 1, H, G, syndroms, 3)

u:  [1]
v:  [1. 1. 1. 1.]
Ошибки:  [1 2 0]
Полученное кодовое слово с ошибкой:  [0. 0. 0. 1.]
Синдромы для этого кодового слова:  [0. 0. 1.]
Обнаружена ошибка!
[0. 0. 0. 1.]
Восстановленное слово:  [0. 0. 0. 0.]
Ошибка была исправлена успешно!


r = 3

In [ ]:
G_2, H_2, syndroms_2 = code_cool_h(3)
print(G_2,'\n')
print(H_2,'\n')
print(syndroms_2,'\n')

[[1. 0. 0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 1. 1. 1.]] 

[[1. 1. 1. 1.]
 [1. 1. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]] 

{(0.0, 0.0, 0.0, 1.0): array([0., 0., 0., 0., 0., 0., 0., 1.]), (0.0, 0.0, 1.0, 1.0): array([0., 0., 0., 0., 0., 0., 1., 0.]), (0.0, 1.0, 0.0, 1.0): array([0., 0., 0., 0., 0., 1., 0., 0.]), (1.0, 0.0, 0.0, 1.0): array([0., 0., 0., 0., 1., 0., 0., 0.]), (0.0, 1.0, 1.0, 1.0): array([0., 0., 0., 1., 0., 0., 0., 0.]), (1.0, 0.0, 1.0, 1.0): array([0., 0., 1., 0., 0., 0., 0., 0.]), (1.0, 1.0, 0.0, 1.0): array([0., 1., 0., 0., 0., 0., 0., 0.]), (1.0, 1.0, 1.0, 1.0): array([1., 0., 0., 0., 0., 0., 0., 0.])} 



Однократная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 1)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0. 1.]
Ошибки:  [1]
Полученное кодовое слово с ошибкой:  [1. 1. 0. 1. 1. 0. 0. 1.]
Синдромы для этого кодового слова:  [1. 1. 0. 1.]
Обнаружена ошибка!
[0. 1. 0. 0. 0. 0. 0. 0.]
Восстановленное слово:  [1. 0. 0. 1. 1. 0. 0. 1.]
Ошибка была исправлена успешно!


Двухкратная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 2)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0. 1.]
Ошибки:  [1 4]
Полученное кодовое слово с ошибкой:  [1. 1. 0. 1. 0. 0. 0. 1.]
Синдромы для этого кодового слова:  [0. 1. 0. 0.]
Обнаружена ошибка!
None
Синдрома нет в таблице, ошибка не исправлена.


Трехкратная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 3)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0. 1.]
Ошибки:  [3 2 1]
Полученное кодовое слово с ошибкой:  [1. 1. 1. 0. 1. 0. 0. 1.]
Синдромы для этого кодового слова:  [0. 0. 0. 1.]
Обнаружена ошибка!
[0. 0. 0. 0. 0. 0. 0. 1.]
Восстановленное слово:  [1. 1. 1. 0. 1. 0. 0. 0.]
Ошибка была исправлена успешно!


Четырехкратная

In [ ]:
word = [1,0,0,1]
code_syndrom_error(word, 7, 4, H_2, G_2, syndroms_2, 4)

u:  [1, 0, 0, 1]
v:  [1. 0. 0. 1. 1. 0. 0. 1.]
Ошибки:  [4 3 5 6]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 0. 0. 1. 1. 1.]
Синдромы для этого кодового слова:  [1. 0. 0. 0.]
Обнаружена ошибка!
None
Синдрома нет в таблице, ошибка не исправлена.


r = 4

In [ ]:
G_3, H_3, syndroms_3 = code_cool_h(4)
print(G_3,'\n')
print(H_3,'\n')
print(syndroms_3,'\n')

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1.]] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1.]
 [0. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1.]] 

{(0.0, 0.0, 0.0, 0.0, 1.0): array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]), (0.0, 0.0, 0.0, 1.0, 1.0): array([0., 0., 0.

Однократная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 1)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
Ошибки:  [12]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
Синдромы для этого кодового слова:  [0. 1. 0. 0. 1.]
Обнаружена ошибка!
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
Восстановленное слово:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
Ошибка была исправлена успешно!


Двухкратная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 2)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
Ошибки:  [11 10]
Полученное кодовое слово с ошибкой:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 1. 0. 1.]
Синдромы для этого кодового слова:  [1. 0. 1. 1. 0.]
Обнаружена ошибка!
None
Синдрома нет в таблице, ошибка не исправлена.


Трехкратная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 3)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
Ошибки:  [ 1 12  4]
Полученное кодовое слово с ошибкой:  [1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
Синдромы для этого кодового слова:  [1. 1. 0. 1. 1.]
Обнаружена ошибка!
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Восстановленное слово:  [1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
Ошибка была исправлена успешно!


Четырехкратная

In [ ]:
word = [1,0,0,1,0,0,1,0,1,1,1]
code_syndrom_error(word, 15, 11, H_3, G_3, syndroms_3, 4)

u:  [1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1]
v:  [1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
Ошибки:  [ 3  0  5 12]
Полученное кодовое слово с ошибкой:  [0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1.]
Синдромы для этого кодового слова:  [1. 1. 0. 0. 0.]
Обнаружена ошибка!
None
Синдрома нет в таблице, ошибка не исправлена.
